/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonNewRouteImport } from './routes/pokemon/new'
import { Route as PokemonPokemonIdIndexRouteImport } from './routes/pokemon/$pokemonId/index'
import { Route as PokemonPokemonIdEditRouteImport } from './routes/pokemon/$pokemonId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonNewRoute = PokemonNewRouteImport.update({
  id: '/pokemon/new',
  path: '/pokemon/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonPokemonIdIndexRoute = PokemonPokemonIdIndexRouteImport.update({
  id: '/pokemon/$pokemonId/',
  path: '/pokemon/$pokemonId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonPokemonIdEditRoute = PokemonPokemonIdEditRouteImport.update({
  id: '/pokemon/$pokemonId/edit',
  path: '/pokemon/$pokemonId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemon/new': typeof PokemonNewRoute
  '/pokemon/$pokemonId/edit': typeof PokemonPokemonIdEditRoute
  '/pokemon/$pokemonId/': typeof PokemonPokemonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemon/new': typeof PokemonNewRoute
  '/pokemon/$pokemonId/edit': typeof PokemonPokemonIdEditRoute
  '/pokemon/$pokemonId': typeof PokemonPokemonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokemon/new': typeof PokemonNewRoute
  '/pokemon/$pokemonId/edit': typeof PokemonPokemonIdEditRoute
  '/pokemon/$pokemonId/': typeof PokemonPokemonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pokemon/new'
    | '/pokemon/$pokemonId/edit'
    | '/pokemon/$pokemonId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemon/new' | '/pokemon/$pokemonId/edit' | '/pokemon/$pokemonId'
  id:
    | '__root__'
    | '/'
    | '/pokemon/new'
    | '/pokemon/$pokemonId/edit'
    | '/pokemon/$pokemonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonNewRoute: typeof PokemonNewRoute
  PokemonPokemonIdEditRoute: typeof PokemonPokemonIdEditRoute
  PokemonPokemonIdIndexRoute: typeof PokemonPokemonIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/new': {
      id: '/pokemon/new'
      path: '/pokemon/new'
      fullPath: '/pokemon/new'
      preLoaderRoute: typeof PokemonNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$pokemonId/': {
      id: '/pokemon/$pokemonId/'
      path: '/pokemon/$pokemonId'
      fullPath: '/pokemon/$pokemonId/'
      preLoaderRoute: typeof PokemonPokemonIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$pokemonId/edit': {
      id: '/pokemon/$pokemonId/edit'
      path: '/pokemon/$pokemonId/edit'
      fullPath: '/pokemon/$pokemonId/edit'
      preLoaderRoute: typeof PokemonPokemonIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonNewRoute: PokemonNewRoute,
  PokemonPokemonIdEditRoute: PokemonPokemonIdEditRoute,
  PokemonPokemonIdIndexRoute: PokemonPokemonIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
